function C = bus_contracts()
%BUS_CONTRACTS 单一权威契约表（机器可读，编码 docs/product/10_Interface_Definition §4 A2 契约）。
%   返回结构体数组，每行一个 Bus：
%     name      — Bus 类型名（= cfg.busName，对应 1_Data_Dictionaries/BusConfig/config_<name>.m）
%     contract  — 契约标识（契约 #N / DEC-xxx）
%     purpose   — 该 Bus 的契约用途（一句话，维护/对账用）
%     expected  — 期望字段元组 N×3 cell {name, type, dims}，逐项必须存在
%     forbidden — 禁止字段 cell（判据泄漏/任务语义/旧字段），一个都不允许出现
%
%   用途：test_bus_contracts.m 批量校验的数据源。本表是"契约的机器编码"，
%         与 10_Interface_Definition §4 保持同步；字段级明细变更在此修改。

C = [ ...
  bc('NavigationContractBus', '契约 #1 v2（DEC-085）', '运动学合同（段=run）：过点序列 + 终止停点，判据归 MM', ...
    { {'ContractId','uint32',1}, {'PlanId','uint32',1}, {'SegmentIndex','uint32',1}, ...
      {'StartValid','boolean',1}, {'StartPositionNED','single',3}, {'PassCount','uint8',1}, ...
      {'PassPositionNED','single','[64 3]'}, {'EndPositionNED','single',3}, ...
      {'CruiseSpeed','single',1}, {'MaxAcceleration','single',1}, {'MaxJerk','single',1}, ...
      {'TargetYaw','single',1}, {'Valid','boolean',1} }, ...
    { 'AcceptanceRadius','RequiredStableTime','PathType','TerminalVelocityNED','ExitDirectionNED', ...
      'ItemType','ObjectiveType' }); ...

  bc('TrajectorySetpointBus', '契约 #2（DEC-086）', 'Navigator→FC 连续轨迹参考（直连强时序）：位置/速度/偏航/Valid', ...
    { {'Position_NED_SP','single',3}, {'Velocity_NED_SP','single',3}, {'Yaw_SP','single',1}, {'Valid','boolean',1} }, ...
    { 'Mode','ArmRequest' }); ...

  bc('StateEstBus', '契约 #3（DEC-073）', 'SE→FC 全量状态估计（直连强时序）：状态 + 诊断项 + Status', ...
    { {'Position_NED','single',3}, {'Velocity_NED','single',3}, {'Attitude_quat','single',4}, ...
      {'AngularRate_Body','single',3}, {'Accel_Body','single',3}, {'GyroBias','single',3}, ...
      {'AccelBias','single',3}, {'Wind_NED','single',3}, {'Status','uint8',1} }, ...
    { 'ItemType','ObjectiveType' }); ...

  bc('StateSnapshot', '契约 #4（DEC-073/074）', 'SE→Navigator 段边界锚点：仅位置/速度，不含偏航', ...
    { {'Position_NED','single',3}, {'Velocity_NED','single',3} }, ...
    { 'Yaw','Attitude','AngularRate' }); ...

  bc('MissionPlanBus', '契约 #5（DEC-088）', 'A1 航线快照（定长 400 扁平）：Meta/Coord/Config + Waypoint[400]', ...
    { {'TaskId','uint32',1}, {'Version','uint32',1}, {'Timestamp','double',1}, ...
      {'Frame','uint8',1}, {'ReferencePointNED','single',3}, {'HeightRef','uint8',1}, ...
      {'FinishAction','uint8',1}, {'LinkLossDefault','uint8',1}, {'SafeTakeoffHeight','single',1}, ...
      {'DepartureSpeed','single',1}, {'DefaultSpeed','single',1}, {'DefaultClimbRate','single',1}, ...
      {'ArrivalDefault','single',4}, {'DefaultYawMode','uint8',1}, ...
      {'WaypointCount','uint16',1}, {'Lat','single',400}, {'Lon','single',400}, {'Height','single',400}, ...
      {'Speed','single',400}, {'ClimbRate','single',400}, {'PassMode','uint8',400}, ...
      {'YawMode','uint8',400}, {'YawParam','single',400}, {'ArrivalPos','single',400}, ...
      {'ArrivalVel','single',400}, {'ArrivalAlt','single',400}, {'ArrivalYaw','single',400}, ...
      {'ActionTrigger','uint8',400}, {'ActionCount','uint8',400}, {'PayloadValid','boolean',400}, ...
      {'IsRisky','boolean',400}, {'CoordinatedTurn','boolean',400}, {'Valid','boolean',1} }, ...
    { 'ItemType','AcceptanceRadius','TerminalBehavior','AdvancePolicy','AutoContinue','DwellTime','MaxJerk' }); ...

  bc('MissionPlanAvailableBus', '契约 #5 / MM-004/005', '计划可用通知：Available + ReasonCode + PlanId（数据通道状态流）', ...
    { {'Available','boolean',1}, {'ReasonCode','uint16',1}, {'PlanId','uint32',1}, {'Valid','boolean',1} }, ...
    { 'RepositoryReady','UploadSequence','Revision','ItemCount' }); ...

  bc('CommanderRequestBus', '契约 #6（DEC-066/089）', 'GCS 写命令请求：CommandId + Command 枚举 + Params + Valid', ...
    { {'CommandId','uint32',1}, {'Command','uint8',1}, {'Params','single',8}, {'Valid','boolean',1} }, ...
    { 'RequestType','RequestedOwner','RequestId' }); ...

  bc('CommandAckBus', '契约 #6（DEC-089/090）', '命令结果逐条 Ack（多事件时序）：CommandId/Result/ReasonCode/Message/Valid', ...
    { {'CommandId','uint32',1}, {'Result','uint8',1}, {'ReasonCode','uint16',1}, {'Message','uint8',32}, {'Valid','boolean',1} }, ...
    { 'ResultCode' }); ...

  bc('CommanderStatusBus', '契约 #6（CMD-006）', 'Commander 状态流：Armed/CurrentMode/LastCommandResult + 安全字段占位', ...
    { {'Armed','boolean',1}, {'CurrentMode','uint8',1}, {'LastCommandResult','uint8',1}, ...
      {'LastCommandId','uint32',1}, {'SafetyState','uint8',1}, {'SafetyDirective','uint8',1}, ...
      {'MissionDirective','uint8',1}, {'FailsafeActive','boolean',1}, {'Valid','boolean',1} }, ...
    { 'AuthorityState','ControlOwner','MissionExecutionAllowed','ActuatorEnabled','ArmingState' }); ...

  bc('MissionControlRequestBus', '契约 #6 路由（DEC-066/101/102）', 'Commander→MM 操作请求：Action 集 = 模式级命令 + go-to-point', ...
    { {'RequestId','uint32',1}, {'CommandId','uint32',1}, {'Action','uint8',1}, ...
      {'TargetPositionNED','single',3}, {'Valid','boolean',1} }, ...
    { 'TargetItemIndex','TargetAltitude_m','PlanId' }); ...

  bc('MissionStatusBus', 'MM-018（DEC-087/067）', 'MM 任务状态流：任务状态 + 进度标签 + 可行性标志位', ...
    { {'PlanId','uint32',1}, {'PlanValid','boolean',1}, {'ExecutionPhase','uint8',1}, ...
      {'MissionOutcome','uint8',1}, {'MissionReason','uint8',1}, {'CurrentItemIndex','uint8',1}, ...
      {'ItemCount','uint8',1}, {'ReachedItemIndex','int16',1}, {'ActiveContractId','uint32',1}, ...
      {'ExecutionHealthy','boolean',1}, {'MissionFaultCode','uint16',1}, {'LandingCompleted','boolean',1}, ...
      {'Valid','boolean',1} }, ...
    { 'State','Completed','Failure' }); ...

  bc('NavigationStatusBus', 'NAV-005（DEC-087）', 'Navigator 制导状态流：制导状态 + Valid（无正常流回报/判据）', ...
    { {'ContractId','uint32',1}, {'GuidanceState','uint8',1}, {'Valid','boolean',1} }, ...
    { 'TerminalConditionSatisfied','RemainingDistance','ObjectiveId','AcceptanceRadius' }); ...

  bc('EscCmdBus', '契约 #7（DEC-064）', 'FC→电调指令（执行链末端直连）：电机[4] + Armed + Valid', ...
    { {'MotorCmd','single',4}, {'Armed','boolean',1}, {'Valid','boolean',1} }, ...
    { 'Position_NED' }); ...

  bc('GPSBus', '契约 #7', 'GPS 测量帧（中速直连）：经纬高 + NED 速度 + Valid/Timestamp/IsNew', ...
    { {'Lat','single',1}, {'Lon','single',1}, {'Alt','single',1}, {'Velocity','single',3}, ...
      {'Valid','boolean',1}, {'Timestamp','double',1}, {'IsNew','boolean',1} }, ...
    { 'Position_NED' }); ...

  bc('IMUBus', '契约 #7', 'IMU 测量帧（高速直连）：比力/角速度 + Valid/Timestamp/IsNew', ...
    { {'Accel','single',3}, {'Gyro','single',3}, {'Valid','boolean',1}, {'Timestamp','double',1}, {'IsNew','boolean',1} }, ...
    { 'Position' }); ...

  bc('DynamicModelBus', '契约 #7', 'MIL plant 动力学真值（真值评估用，非控制输入）', ...
    { {'Position_NED','single',3}, {'Velocity_NED','single',3}, {'Attitude_quat','single',4}, ...
      {'AngularRate_Body','single',3}, {'Accel_Body','single',3} }, ...
    { 'FlightCmd' }); ...

  bc('ThrustTorqueBus', '契约 #7', '动力→动力学 合力/力矩（plant 路径）', ...
    { {'Thrust_Body','single',3}, {'Torque_Body','single',3} }, ...
    { 'Position' }); ...

  bc('RuntimeTruthBus', '契约 #7', '运行时真值帧（实验分析，非 FlightCore 输入）', ...
    { {'SourceId','uint16',1}, {'Sequence','uint32',1}, {'Timestamp','double',1}, ...
      {'Position_NED','single',3}, {'Velocity_NED','single',3}, {'Valid','boolean',1} }, ...
    { 'EscMotorCmd' }); ...

  bc('ExperimentTraceBus', '契约 #7', '最小实验跟踪帧：真值 + 传感器 + 估计 + 执行器 + 误差', ...
    { {'SourceId','uint16',1}, {'Sequence','uint32',1}, {'Timestamp','double',1}, {'Valid','boolean',1}, ...
      {'TruthPosition_NED','single',3}, {'IMUAccel','single',3}, {'GPS_LLA','single',3}, ...
      {'StatePosition_NED','single',3}, {'EscMotorCmd','single',4}, {'PositionError_NED','single',3} }, ...
    { 'Waypoint','ItemType' }); ...

  bc('RouteWindowBus', 'MM 内部（随 MM 重构对齐）', 'MM 内部段滑动窗口（不跨模块），核心结构锁定', ...
    { {'PlanId','uint32',1}, {'ItemIndex','uint8',1}, {'PreviousValid','boolean',1}, ...
      {'PreviousPositionNED','single',3}, {'CurrentPositionNED','single',3}, ...
      {'NextPositionNED','single',3}, {'IsFirstItem','boolean',1}, {'IsLastItem','boolean',1}, ...
      {'Valid','boolean',1} }, ...
    { }); ...

  bc('GcsLinkStatusBus', '契约 #7', '链路状态（遥测/起飞门输入）：Connected + LinkQuality + Valid', ...
    { {'SourceId','uint32',1}, {'RxSequence','uint32',1}, {'LastRxTimeSec','double',1}, ...
      {'LinkQuality','single',1}, {'Connected','boolean',1}, {'Valid','boolean',1} }, ...
    { }); ...
];

end

function e = bc(name, contract, purpose, expected, forbidden)
%B 构建单个契约表条目。
e = struct();
e.name = name;
e.contract = contract;
e.purpose = purpose;
e.expected = expected;    % N×3 cell {name,type,dims}
e.forbidden = forbidden;  % 1×K cell
end
