function test_runtime_adapter_isolation_contract()
% test_runtime_adapter_isolation_contract verifies simulator isolation docs.

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
contractPath = fullfile(projectRoot, 'docs', 'architecture', ...
    'flightcore_runtime_isolation.md');

assert(isfile(contractPath), ...
    'Missing architecture contract: docs/architecture/flightcore_runtime_isolation.md');

text = fileread(contractPath);

requiredTerms = { ...
    'FlightCore', ...
    'InterfaceContract', ...
    'RuntimeAdapter', ...
    'SensorInput', ...
    'CommandInput', ...
    'ActuatorOutput', ...
    'EstimatorInit', ...
    'Telemetry', ...
    'InternalSimAdapter', ...
    'PegasusAdapter', ...
    'AirSimAdapter', ...
    'ROS2Adapter', ...
    'BoardHALAdapter'};

for i = 1:numel(requiredTerms)
    assert(contains(text, requiredTerms{i}), ...
        'Architecture contract must define %s.', requiredTerms{i});
end

flightCoreSection = extractRequiredSection(text, ...
    '## FlightCore Boundary', '## Interface Contract');
forbiddenTerms = {'AirSim', 'Isaac', 'Pegasus', 'ROS2', 'MAVLink', ...
    'simSetVehiclePose', 'moveByMotorPWMsAsync', 'USD'};

for i = 1:numel(forbiddenTerms)
    assert(~contains(flightCoreSection, forbiddenTerms{i}), ...
        'FlightCore Boundary must not leak simulator-specific term: %s.', forbiddenTerms{i});
end

adapterSection = extractRequiredSection(text, ...
    '## Runtime Adapters', '## Implementation Order');
adapterTerms = {'PegasusAdapter', 'AirSimAdapter', 'InternalSimAdapter', ...
    'ROS2Adapter', 'BoardHALAdapter', 'HILAdapter', 'SILAdapter'};

for i = 1:numel(adapterTerms)
    assert(contains(adapterSection, adapterTerms{i}), ...
        'Runtime Adapters section must define %s.', adapterTerms{i});
end

assert(contains(text, 'ScenarioConfig is not a runtime data bus'), ...
    'ScenarioConfig must be explicitly excluded from the runtime data bus role.');

disp('RUNTIME_ADAPTER_ISOLATION_CONTRACT_PASS');
end

function section = extractRequiredSection(text, startMarker, endMarker)
startIdx = strfind(text, startMarker);
assert(~isempty(startIdx), 'Missing section marker: %s.', startMarker);
startIdx = startIdx(1);

endIdx = strfind(text(startIdx:end), endMarker);
assert(~isempty(endIdx), 'Missing section marker: %s.', endMarker);
endIdx = startIdx + endIdx(1) - 2;

section = text(startIdx:endIdx);
end
