function test_qgc_ten_waypoint_land_contract()
%TEST_QGC_TEN_WAYPOINT_LAND_CONTRACT Static target-architecture contract.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
flightCorePath = fullfile(projectRoot, '3_Integration', 'FlightCore', ...
    'FlightCore.slx');
gazeboPath = fullfile(projectRoot, '3_Integration', ...
    'FlightCore_Gazebo_loop.slx');
gatewayPath = fullfile(projectRoot, '3_Integration', 'MAVLink', ...
    'Gateway.slx');
protocolPath = fullfile(projectRoot, '3_Integration', 'MAVLink', ...
    'GatewayMavlinkProtocol.slx');

load_system(flightCorePath);
load_system(gazeboPath);
load_system(gatewayPath);
load_system(protocolPath);

gatewayRefs = find_system('FlightCore', 'SearchDepth', 1, ...
    'BlockType', 'ModelReference', 'ModelName', 'Gateway');
assert(numel(gatewayRefs) == 1, ...
    'FlightCore must own exactly one Gateway model-reference component.');

flightCoreInputs = get_param(find_system('FlightCore', 'SearchDepth', 1, ...
    'BlockType', 'Inport'), 'Name');
assert(~any(strcmp(flightCoreInputs, 'MissionPlan')), ...
    'MissionPlan must be produced by the internal Gateway component.');
assert(~any(strcmp(flightCoreInputs, 'CommandIngressSnapshot')), ...
    'Command ingress must be produced by the internal Gateway component.');
assert(isequal(flightCoreInputs, {'IMU_BUS'; 'GPS_BUS'}), ...
    'FlightCore external boundary must remain limited to IMU and GPS.');

gatewayInputs = get_param(find_system('Gateway', 'SearchDepth', 1, ...
    'BlockType', 'Inport'), 'Name');
assert(isequal(gatewayInputs, {'HomeLLA'; 'HomeValid'}), ...
    'Gateway must accept only the local-origin conversion inputs.');
protocolRefs = find_system('Gateway', 'SearchDepth', 1, ...
    'BlockType', 'ModelReference', ...
    'ModelName', 'GatewayMavlinkProtocol');
assert(numel(protocolRefs) == 1, ...
    'Gateway must own exactly one official MAVLink protocol component.');
interpretedBlocks = find_system('Gateway', 'LookUnderMasks', 'all', ...
    'FollowLinks', 'on', 'BlockType', 'MATLABFcn');
assert(isempty(interpretedBlocks), ...
    'Gateway must not contain Interpreted MATLAB Function blocks.');

injected = find_system('FlightCore_Gazebo_loop', 'SearchDepth', 1, ...
    'Name', 'InjectedMissionScenario');
assert(isempty(injected), ...
    'Gazebo harness must not inject a private mission scenario.');

creator = find_system('Gateway', 'LookUnderMasks', 'all', ...
    'FollowLinks', 'on', 'Name', 'CreateMissionPlan');
assert(numel(creator) == 1, ...
    'Gateway must contain exactly one MissionPlan bus creator.');
assert(strcmp(get_param(creator{1}, 'Inputs'), '13'), ...
    'Gateway MissionPlan creator must match the 13-field current bus.');

gatewayLines = find_system('Gateway', 'FindAll', 'on', 'Type', 'line');
gatewaySignalNames = string(get_param(gatewayLines, 'Name'));
assert(~any(gatewaySignalNames == "HoldTime") && ...
    ~any(gatewaySignalNames == "AutoContinue"), ...
    'Gateway must not retain obsolete MissionPlan signal labels.');
assert(any(gatewaySignalNames == "TerminalBehavior") && ...
    any(gatewaySignalNames == "AdvancePolicy"), ...
    'Gateway must label MissionPlan signals with the current bus fields.');

missionStatusBus = Simulink.data.evalinGlobal( ...
    'FlightCore', 'MissionStatusBus');
missionStatusNames = string({missionStatusBus.Elements.Name});
assert(any(missionStatusNames == "LandingCompleted"), ...
    'MissionStatus must report the completed LAND fact to Commander.');

open_system(fullfile(projectRoot, '2_Model', 'commander', 'Commander.slx'));
armingChart = find(sfroot, '-isa', 'Stateflow.State', ...
    'Name', 'ArmingRegion');
assert(numel(armingChart) == 1 && ...
    contains(string(armingChart.LabelString), ...
    'MissionStatus.LandingCompleted'), ...
    'Commander must automatically disarm after a completed LAND item.');

open_system(fullfile(projectRoot, '2_Model', 'navigator', 'Navigator.slx'));
trajectoryFunction = find(sfroot, '-isa', 'Stateflow.EMChart', ...
    'Name', 'StopAndGoTrajectory');
assert(numel(trajectoryFunction) == 1, ...
    'Navigator must contain one stop-and-go trajectory generator.');
trajectoryScript = string(trajectoryFunction.Script);
assert(contains(trajectoryScript, 'contract.CruiseSpeed') && ...
    contains(trajectoryScript, 'contract.MaxAcceleration') && ...
    contains(trajectoryScript, 'contract.MaxJerk') && ...
    contains(trajectoryScript, 'stopVelocityTolerance'), ...
    'Navigator trajectory generator must enforce speed, acceleration, jerk, and stop velocity.');

fprintf('QGC_TEN_WAYPOINT_LAND_CONTRACT_PASS\n');
end
