function test_gazebo_lightweight_lockstep_contract()
%TEST_GAZEBO_LIGHTWEIGHT_LOCKSTEP_CONTRACT Verify blocking lockstep boundaries.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
repositoryRoot = fileparts(projectRoot);
integrationRoot = fullfile(projectRoot, '3_Integration');
gazeboRoot = fullfile(repositoryRoot, 'bridge', 'wsl', 'packages', 'gazebo');
matlabMessageRoot = fullfile(integrationRoot, 'ROS2', ...
    'flightcore_gazebo_msgs', 'msg');
wslMessageRoot = fullfile(gazeboRoot, 'flightcore_gazebo_msgs', 'msg');
matlabCommonMessageRoot = fullfile(integrationRoot, 'ROS2', ...
    'flightcore_msgs', 'msg');
wslCommonMessageRoot = fullfile(repositoryRoot, 'bridge', 'wsl', ...
    'packages', 'common', 'flightcore_msgs', 'msg');
matlabServiceRoot = fullfile(integrationRoot, 'ROS2', ...
    'flightcore_gazebo_msgs', 'srv');
wslServiceRoot = fullfile(gazeboRoot, 'flightcore_gazebo_msgs', 'srv');
pluginPath = fullfile(gazeboRoot, 'flightcore_gazebo_system', 'src', ...
    'flightcore_gazebo_system.cpp');
pluginCmakePath = fullfile(gazeboRoot, 'flightcore_gazebo_system', ...
    'CMakeLists.txt');
pluginPackagePath = fullfile(gazeboRoot, 'flightcore_gazebo_system', ...
    'package.xml');
coordinatorPath = fullfile(gazeboRoot, ...
    'flightcore_simulation_coordinator', 'src', ...
    'flightcore_simulation_coordinator.cpp');
coordinatorCmakePath = fullfile(gazeboRoot, ...
    'flightcore_simulation_coordinator', 'CMakeLists.txt');
pluginLaunchPath = fullfile(gazeboRoot, 'flightcore_gazebo_system', ...
    'launch', 'flightcore_gazebo_cosim.launch.py');
readinessPath = fullfile(repositoryRoot, 'bridge', 'wsl', 'scripts', ...
    'wait_flightcore_gazebo_ready.py');
entryPath = fullfile(repositoryRoot, 'orchestration', ...
    'run_flightcore_gazebo.ps1');
messageGeneratorPath = fullfile(integrationRoot, 'ROS2', ...
    'generate_flightcore_ros2_messages.m');

requiredFiles = {
    pluginPath
    pluginCmakePath
    pluginPackagePath
    coordinatorPath
    coordinatorCmakePath
    pluginLaunchPath
    readinessPath
    entryPath
    messageGeneratorPath
    fullfile(matlabMessageRoot, 'ActuatorCommand.msg')
    fullfile(wslMessageRoot, 'ActuatorCommand.msg')
    fullfile(matlabCommonMessageRoot, 'Imu.msg')
    fullfile(wslCommonMessageRoot, 'Imu.msg')
    fullfile(matlabCommonMessageRoot, 'Gps.msg')
    fullfile(wslCommonMessageRoot, 'Gps.msg')
    fullfile(matlabMessageRoot, 'PlantStepDone.msg')
    fullfile(wslMessageRoot, 'PlantStepDone.msg')
    fullfile(matlabMessageRoot, 'ResultReady.msg')
    fullfile(wslMessageRoot, 'ResultReady.msg')
    fullfile(matlabMessageRoot, 'CommitRelease.msg')
    fullfile(wslMessageRoot, 'CommitRelease.msg')
    fullfile(matlabServiceRoot, 'PrimeSession.srv')
    fullfile(wslServiceRoot, 'PrimeSession.srv')
    };
for i = 1:numel(requiredFiles)
    assert(isfile(requiredFiles{i}), ...
        'Missing blocking lockstep file: %s', requiredFiles{i});
end

obsoletePaths = {
    fullfile(integrationRoot, 'Gazebo', ...
        'BlockingStepResultSubscriber.m')
    fullfile(integrationRoot, 'Gazebo', ...
        'BlockingLockstepAcceptance.m')
    fullfile(integrationRoot, 'Gazebo', ...
        'ControlGrantBlockingSubscriber.m')
    fullfile(integrationRoot, 'Gazebo', ...
        'FlightCoreGazeboCoSimDriver.m')
    fullfile(integrationRoot, 'Gazebo', ...
        'SimulinkParticipantAdapter.m')
    fullfile(integrationRoot, 'ROS2', ...
        'simulation_coordinator_interfaces')
    fullfile(matlabMessageRoot, 'StepResult.msg')
    fullfile(wslMessageRoot, 'StepResult.msg')
    };
for i = 1:numel(obsoletePaths)
    assert(~isfile(obsoletePaths{i}) && ~isfolder(obsoletePaths{i}), ...
        'Obsolete lockstep route remains: %s', obsoletePaths{i});
end

actuatorFields = {
    'uint64 source_step_id'
    'uint64 target_step_id'
    'uint64 command_id'
    'uint64 valid_from_iteration'
    'float32[4] actuator_values'
    };

assertMirroredMessage( ...
    fullfile(matlabMessageRoot, 'ActuatorCommand.msg'), ...
    fullfile(wslMessageRoot, 'ActuatorCommand.msg'), actuatorFields);
assertMirroredMessage( ...
    fullfile(matlabCommonMessageRoot, 'Imu.msg'), ...
    fullfile(wslCommonMessageRoot, 'Imu.msg'), ...
    {'float32[3] accel_mps2', 'float32[3] gyro_radps'});
assertMirroredMessage( ...
    fullfile(matlabCommonMessageRoot, 'Gps.msg'), ...
    fullfile(wslCommonMessageRoot, 'Gps.msg'), ...
    {'float32 lat_deg', 'float32 lon_deg', 'float32 alt_m'});
assertMirroredMessage( ...
    fullfile(matlabMessageRoot, 'PlantStepDone.msg'), ...
    fullfile(wslMessageRoot, 'PlantStepDone.msg'), ...
    {'uint64 session_id', 'uint64 step_id', 'bool accepted'});
assertMirroredMessage( ...
    fullfile(matlabMessageRoot, 'ResultReady.msg'), ...
    fullfile(wslMessageRoot, 'ResultReady.msg'), ...
    {'uint64 session_id', 'uint64 step_id', 'bool accepted'});
assertMirroredMessage( ...
    fullfile(matlabMessageRoot, 'CommitRelease.msg'), ...
    fullfile(wslMessageRoot, 'CommitRelease.msg'), ...
    {'uint64 session_id', 'uint64 step_id', 'bool accepted'});

pluginText = fileread(pluginPath);
assert(contains(pluginText, 'source_step_id'), ...
    'Gazebo plugin must validate the command source step.');
assert(contains(pluginText, 'target_step_id'), ...
    'Gazebo plugin must validate the command target step.');
assert(contains(pluginText, 'on_blocking_actuator_command'), ...
    'Gazebo plugin must expose the command-triggered one-step callback.');
assert(contains(pluginText, 'publish_sensor_snapshot'), ...
    'Gazebo plugin must publish released IMU/GPS sensor snapshots.');
assert(contains(pluginText, '/flightcore/gazebo/imu') && ...
    contains(pluginText, '/flightcore/gazebo/gps') && ...
    contains(pluginText, 'create_publisher<Imu>') && ...
    contains(pluginText, 'create_publisher<Gps>'), ...
    'Gazebo plugin must expose separate native IMU and GPS publishers.');
assert(~contains(pluginText, 'StepResult') && ...
    ~contains(pluginText, 'step_result'), ...
    'Gazebo plugin must not retain StepResult.');
assert(~contains(pluginText, 'payload_hash'), ...
    'The lightweight Gazebo path must not introduce payload hash.');
assert(~contains(pluginText, 'gz::transport::Node') && ...
    ~contains(pluginText, 'gz::msgs::WorldControl') && ...
    ~contains(pluginText, 'enqueue_world_control') && ...
    ~contains(pluginText, 'on_world_control_response'), ...
    'Gazebo plugin callback must not own or call WorldControl.');
assert(contains(pluginText, 'command_cached_pub_->publish(cached)') && ...
    contains(pluginText, 'on_commit_release') && ...
    contains(pluginText, 'result_ready_pub_->publish(result_ready)') && ...
    contains(pluginText, 'plant_step_done_pub_->publish(plant_done)'), ...
    'Gazebo plugin must cache/ACK and wait for CommitRelease.');
assert(~contains(pluginText, 'best_effort()') && ...
    ~contains(pluginText, 'on_result_retry') && ...
    contains(pluginText, 'KeepLast(10)).reliable()'), ...
    'IMU/GPS transport must be Reliable without StepResult retry state.');
assert(contains(pluginText, 'on_prime_session') && ...
    contains(pluginText, 'initial_snapshot_ready_'), ...
    'Gazebo plugin must expose a PRIME-only initial-session path.');
assert(~contains(pluginText, 'on_reset_session') && ...
    ~contains(pluginText, 'reset_session') && ...
    ~contains(pluginText, 'mutable_reset()'), ...
    'Fresh-process startup must not retain a Gazebo RESET path.');
assert(~contains(pluginText, 'ros_gz_interfaces/srv/control_world.hpp'), ...
    'Gazebo plugin must not route world control back through ROS 2.');
assert(~contains(pluginText, 'control_client_'), ...
    'Gazebo plugin must not retain a ROS 2 ControlWorld client.');
assert(contains(pluginText, '/flightcore/gazebo/commit_release'), ...
    'Gazebo plugin must subscribe to Coordinator CommitRelease.');
assert(~contains(pluginText, 'tcp_server') && ...
    ~contains(pluginText, 'matlab_apply_and_step'), ...
    'Gazebo plugin must not retain obsolete TCP or Trigger compatibility paths.');
assert(~contains(pluginText, '/flightcore/gazebo/sensors/imu') && ...
    ~contains(pluginText, '/flightcore/gazebo/sensors/gps') && ...
    ~contains(pluginText, '/flightcore/gazebo/actuator/esc_cmd'), ...
    'Gazebo route must not retain obsolete nested sensor/ESC topics.');

pluginCmakeText = fileread(pluginCmakePath);
pluginPackageText = fileread(pluginPackagePath);
pluginLaunchText = fileread(pluginLaunchPath);
readinessText = fileread(readinessPath);
assert(~contains(pluginCmakeText, 'ros_gz_interfaces'), ...
    'Native world control must not link ros_gz_interfaces.');
assert(~contains(pluginPackageText, '<depend>ros_gz_interfaces</depend>'), ...
    'Native world control must not depend on ros_gz_interfaces.');
assert(~contains(pluginCmakeText, 'gz-transport') && ...
    ~contains(pluginPackageText, '<depend>gz-transport13</depend>'), ...
    'Gazebo plugin must not link the WorldControl transport client.');
assert(~contains(pluginLaunchText, 'parameter_bridge'), ...
    'Runtime launch must not bridge WorldControl through ros_gz_bridge.');
assert(~contains(readinessText, ...
    '"/world/flightcore_world/control" in services'), ...
    'ROS readiness must not require the removed WorldControl bridge.');
assert(contains(readinessText, '"/flightcore/gazebo/prime_session"'), ...
    'ROS readiness must require the PRIME-only service.');
assert(contains(readinessText, '"/flightcore_simulation_coordinator"') && ...
    contains(readinessText, '"/flightcore/gazebo/commit_release"'), ...
    'Readiness must require Coordinator and CommitRelease endpoints.');
assert(contains(readinessText, '"/flightcore/gazebo/imu"') && ...
    contains(readinessText, '"/flightcore/gazebo/gps"') && ...
    ~contains(readinessText, '"/flightcore/gazebo/step_result"'), ...
    'Readiness must match separate IMU/GPS endpoints without StepResult.');
messageGeneratorText = fileread(messageGeneratorPath);
assert(contains(messageGeneratorText, ...
    'flightcore_gazebo_msgs/CommitRelease'), ...
    'MATLAB message generation must validate barrier interfaces.');

coordinatorText = fileread(coordinatorPath);
assert(contains(coordinatorText, 'gz::msgs::WorldControl') && ...
    contains(coordinatorText, 'request.set_multi_step(1)') && ...
    contains(coordinatorText, 'on_world_control_response'), ...
    'Coordinator must be the unique WorldControl owner.');
assert(contains(coordinatorText, 'control_ready_') && ...
    contains(coordinatorText, 'command_cached_') && ...
    contains(coordinatorText, 'plant_step_done_') && ...
    contains(coordinatorText, 'result_ready_'), ...
    'Coordinator must collect pre-step and completion ACKs.');
assert(contains(coordinatorText, 'commit_release_pub_->publish(release)'), ...
    'Coordinator must release payload only after physical completion.');

entryText = fileread(entryPath);
assert(~contains(entryText, 'SimulinkParticipantAdapter'), ...
    'Runtime entry must not use the model-external per-step adapter.');
assert(contains(readinessText, 'flightcore_simulation_coordinator'), ...
    'Runtime readiness must put Coordinator in every epoch path.');
assert(~contains(entryText, 'BlockingLockstepAcceptance') && ...
    ~contains(entryText, 'BlockingStepResultSubscriber') && ...
    contains(entryText, 'generated FlightCore ROS 2 node'), ...
    'Retired Desktop participant entry must fail closed pending generated node.');
modelPath = fullfile(integrationRoot, 'FlightCore_Gazebo_loop.slx');
assert(isfile(modelPath), 'Missing Gazebo-specific Simulink harness.');
load_system(modelPath);
modelCleanup = onCleanup(@() close_system('FlightCore_Gazebo_loop', 0));

sFunctions = find_system('FlightCore_Gazebo_loop', ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'FunctionName', 'BlockingStepResultSubscriber');
assert(isempty(sFunctions), ...
    'Harness runtime must not depend on BlockingStepResultSubscriber.');

stepResultAdapter = find_system('FlightCore_Gazebo_loop', ...
    'SearchDepth', 1, 'BlockType', 'SubSystem', ...
    'Name', 'StepResultAdapter');
assert(isempty(stepResultAdapter), ...
    'Harness must not retain a StepResult adapter subsystem.');
directRoutingBlocks = {
    'GazeboImuSubscribe'
    'GazeboImuSelector'
    'GazeboGpsSubscribe'
    'GazeboGpsSelector'
    };
for i = 1:numel(directRoutingBlocks)
    matches = find_system('FlightCore_Gazebo_loop', ...
        'SearchDepth', 1, 'Name', directRoutingBlocks{i});
    assert(isscalar(matches), ...
        'Missing direct sensor routing block: %s', ...
        directRoutingBlocks{i});
end
removedPlaceholderValidationBlocks = {
    'ExpectedStepClock'
    'TimeToExpectedStep'
    'ExpectedStep'
    'ExpectedStepUint64'
    'ExpectedSimTimeNs'
    'ExpectedSimTimeNsInt64'
    'ExpectedSessionId'
    'SessionMatches'
    'StepMatches'
    'TargetIterationMatches'
    'SimTimeMatches'
    'AppliedCommandMatches'
    'AppliedIterationMatches'
    'AppliedTimeMatches'
    'ExpectedMaskImuOnly'
    'ExpectedMaskImuGps'
    'ExpectedSensorMask'
    'SensorMaskMatches'
    };
for i = 1:numel(removedPlaceholderValidationBlocks)
    matches = find_system('FlightCore_Gazebo_loop', ...
        'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
        'Name', removedPlaceholderValidationBlocks{i});
    assert(isempty(matches), ...
        'Placeholder StepResult validation remains: %s', ...
        removedPlaceholderValidationBlocks{i});
end

oldBlockers = find_system('FlightCore_Gazebo_loop', ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'FunctionName', 'ControlGrantBlockingSubscriber');
assert(isempty(oldBlockers), ...
    'Harness must not retain the old ControlGrant blocker.');

subscribeBlocks = find_system('FlightCore_Gazebo_loop', ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'ReferenceBlock', 'ros2lib/Subscribe');
subscribeTopics = string(get_param(subscribeBlocks, 'topic'));
assert(~any(subscribeTopics == "/flightcore/gazebo/step_result"), ...
    'Harness must not retain a StepResult Subscribe block.');
assert(nnz(subscribeTopics == "/flightcore/gazebo/imu") == 1, ...
    'Harness must contain one native IMU Subscribe block.');
imuSubscribe = subscribeBlocks(subscribeTopics == "/flightcore/gazebo/imu");
assert(strcmp(get_param(imuSubscribe{1}, 'messageType'), ...
    'flightcore_msgs/Imu'), ...
    'IMU Subscribe must use flightcore_msgs/Imu.');
assert(strcmp(get_param(imuSubscribe{1}, 'QOSReliability'), ...
    'Reliable'), ...
    'Generated-node IMU transport must use Reliable QoS.');
assert(nnz(subscribeTopics == "/flightcore/gazebo/gps") == 1, ...
    'Harness must contain one native GPS Subscribe block.');
gpsSubscribe = subscribeBlocks(subscribeTopics == "/flightcore/gazebo/gps");
assert(strcmp(get_param(gpsSubscribe{1}, 'messageType'), ...
    'flightcore_msgs/Gps'), ...
    'GPS Subscribe must use flightcore_msgs/Gps.');
assert(strcmp(get_param(gpsSubscribe{1}, 'QOSReliability'), ...
    'Reliable'), ...
    'Generated-node GPS transport must use Reliable QoS.');

publishBlocks = find_system('FlightCore_Gazebo_loop', ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'ReferenceBlock', 'ros2lib/Publish');
publishTopics = string(get_param(publishBlocks, 'topic'));
assert(nnz(publishTopics == "/flightcore/gazebo/actuator_command") == 1, ...
    'Harness must publish one identity-bearing ActuatorCommand.');
validGate = find_system('FlightCore_Gazebo_loop', ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'Name', 'ActuatorCommandValidGate');
assert(isempty(validGate), ...
    'Harness must not gate ActuatorCommand with removed StepResult state.');
executionCount = find_system('FlightCore_Gazebo_loop', ...
    'SearchDepth', 1, 'Name', 'ExecutionCount');
assert(isscalar(executionCount), ...
    'Harness must derive actuator identity from its execution count.');

fprintf('GAZEBO_NATIVE_ROS2_LOCKSTEP_CONTRACT_PASS\n');
end

function assertMirroredMessage(matlabPath, wslPath, requiredFields)
matlabText = normalizeText(fileread(matlabPath));
wslText = normalizeText(fileread(wslPath));
assert(strcmp(matlabText, wslText), ...
    'MATLAB and WSL message definitions differ: %s', matlabPath);
for i = 1:numel(requiredFields)
    assert(contains(matlabText, requiredFields{i}), ...
        'Missing required field "%s" in %s', requiredFields{i}, matlabPath);
end
assert(~contains(lower(matlabText), 'hash'), ...
    'Lightweight interface must not contain hash: %s', matlabPath);
end

function text = normalizeText(text)
text = regexprep(strtrim(text), '\r\n?', '\n');
end
