function test_gazebo_observation_ready_contract()
%TEST_GAZEBO_OBSERVATION_READY_CONTRACT Verify multi-rate sensor barriers.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
messageRoot = fullfile(projectRoot, '3_Integration', 'ROS2', ...
    'flightcore_gazebo_msgs', 'msg');
generatorPath = fullfile(projectRoot, '3_Integration', 'ROS2', ...
    'generate_flightcore_ros2_messages.m');

batchPath = fullfile(messageRoot, 'SensorBatchPublished.msg');
readyPath = fullfile(messageRoot, 'ObservationReady.msg');
assert(isfile(batchPath), ...
    'Missing Gazebo producer-side SensorBatchPublished contract.');
assert(isfile(readyPath), ...
    'Missing FlightCore consumer-side ObservationReady contract.');

batchText = normalizeText(fileread(batchPath));
readyText = normalizeText(fileread(readyPath));
identityFields = {
    'uint64 session_id'
    'uint64 step_id'
    'uint64 command_id'
    'uint64 iteration'
    'int64 sim_time_ns'
    };
for i = 1:numel(identityFields)
    assert(contains(batchText, identityFields{i}), ...
        'SensorBatchPublished missing identity field: %s', ...
        identityFields{i});
    assert(contains(readyText, identityFields{i}), ...
        'ObservationReady missing identity field: %s', ...
        identityFields{i});
end

assert(contains(batchText, 'uint8 required_mask') && ...
    contains(batchText, 'uint8 published_mask'), ...
    'Gazebo batch contract must declare required and published sensors.');
assert(contains(readyText, 'uint8 required_mask') && ...
    contains(readyText, 'uint8 received_mask'), ...
    'FlightCore ready contract must declare required and received sensors.');
assert(~contains(lower(batchText), 'hash') && ...
    ~contains(lower(readyText), 'hash'), ...
    'Lightweight lockstep contracts must not add payload hashes.');

generatorText = fileread(generatorPath);
assert(contains(generatorText, ...
    'flightcore_gazebo_msgs/SensorBatchPublished'), ...
    'MATLAB message generation must validate SensorBatchPublished.');
assert(contains(generatorText, ...
    'flightcore_gazebo_msgs/ObservationReady'), ...
    'MATLAB message generation must validate ObservationReady.');

fprintf('GAZEBO_OBSERVATION_READY_CONTRACT_PASS\n');
end

function text = normalizeText(text)
text = regexprep(strtrim(text), '\r\n?', '\n');
end
